config/routes.rb
ProductCatalog::Application.routes.draw do
  resources :raw_products

  resources :units

  resources :products

  resources :items

  resources :categories

  authenticated :user do
    root :to => 'items#index'
  end

  root :to => "home#index"

  devise_for :users

  resources :users, :only => [:show, :index]
end

app/models/raw_product.rb
class RawProduct < ActiveRecord::Base
  attr_accessible :id, :title, :category, :subcategory, :per_packet, :length_mm, :memory, :dimensions, :sku, :minimum_order, :item_price, :per_unit, :unit_price, :comment
end

app/controllers/raw_products_controller.rb
class RawProductsController < ApplicationController
  load_and_authorize_resource

  # GET /raw_products
  # GET /raw_products.json
  def index
    @raw_products = RawProduct.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @raw_products }
    end
  end

  # GET /raw_products/1
  # GET /raw_products/1.json
  def show
    @raw_product = RawProduct.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @raw_product }
    end
  end

  # GET /raw_products/new
  # GET /raw_products/new.json
  def new
    @raw_product = RawProduct.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @raw_product }
    end
  end

  # GET /raw_products/1/edit
  def edit
    @raw_product = RawProduct.find(params[:id])
  end

  # POST /raw_products
  # POST /raw_products.json
  def create
    @raw_product = RawProduct.new(params[:raw_product])

    respond_to do |format|
      if @raw_product.save
        format.html { redirect_to @raw_product, notice: 'Raw product was successfully created.' }
        format.json { render json: @raw_product, status: :created, location: @raw_product }
      else
        format.html { render action: "new" }
        format.json { render json: @raw_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /raw_products/1
  # PUT /raw_products/1.json
  def update
    @raw_product = RawProduct.find(params[:id])

    respond_to do |format|
      if @raw_product.update_attributes(params[:raw_product])
        format.html { redirect_to @raw_product, notice: 'Raw product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @raw_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /raw_products/1
  # DELETE /raw_products/1.json
  def destroy
    @raw_product = RawProduct.find(params[:id])
    @raw_product.destroy

    respond_to do |format|
      format.html { redirect_to raw_products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/raw_products_helper.rb
module RawProductsHelper
end

app/views/raw_products/_form.html.haml
= bootstrap_form_for @raw_product do |f|
  - if @raw_product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@raw_product.errors.count, "error")} prohibited this raw_product from being saved:"
      %ul
        - @raw_product.errors.full_messages.each do |msg|
          %li= msg

  = f.text_field :title
  = f.text_field :category
  = f.text_field :subcategory
  = f.text_field :per_packet
  = f.text_field :length_mm
  = f.text_field :memory
  = f.text_field :dimensions
  = f.text_field :sku
  = f.text_field :minimum_order
  = f.text_field :item_price
  = f.text_field :per_unit
  = f.text_field :unit_price
  = f.submit 'Save'

app/views/raw_products/edit.html.haml
%h1 Editing raw_product

= render 'form'

= link_to 'Show', @raw_product
\|
= link_to 'Back', raw_products_path

app/views/raw_products/index.html.haml
%h1 Listing raw_products

%table.table.table-condensed
  %tr
    %th Title
    %th Category
    %th Subcategory
    %th Per packet
    %th Length mm
    %th Memory
    %th Dimensions
    %th SKU
    %th Minimum order
    %th Item price
    %th Per unit
    %th Unit price
    %th Comment
    %th
    %th
    %th

  - @raw_products.each do |raw_product|
    %tr
      %td= raw_product.title
      %td= raw_product.category
      %td= raw_product.subcategory
      %td= raw_product.per_packet
      %td= raw_product.length_mm
      %th= raw_product.memory
      %td= raw_product.dimensions
      %td= raw_product.sku
      %td= raw_product.minimum_order
      %td= raw_product.item_price
      %td= raw_product.per_unit
      %td= raw_product.unit_price
      %td= raw_product.comment
      %td= link_to 'Show', raw_product
      %td= link_to 'Edit', edit_raw_product_path(raw_product)
      %td= link_to 'Destroy', raw_product, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Raw product', new_raw_product_path

app/views/raw_products/new.html.haml
%h1 New raw_product

= render 'form'

= link_to 'Back', raw_products_path

app/views/raw_products/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @raw_product.title
%p
  %b Subcategory:
  = @raw_product.subcategory
%p
  %b Length mm:
  = @raw_product.length_mm
%p
  %b Per packet:
  = @raw_product.per_packet
%p
  %b Dimensions:
  = @raw_product.dimensions
%p
  %b Sku:
  = @raw_product.sku
%p
  %b Minimum order:
  = @raw_product.minimum_order
%p
  %b Item price:
  = @raw_product.item_price
%p
  %b Per unit:
  = @raw_product.per_unit
%p
  %b Unit price:
  = @raw_product.unit_price
%p
  %b Item price:
  = @raw_product.item_price
%p
  %b Min order:
  = @raw_product.min_order
%p
  %b Min order cost:
  = @raw_product.min_order_cost
%p
  %b Blank1:
  = @raw_product.blank1

= link_to 'Edit', edit_raw_product_path(@raw_product)
\|
= link_to 'Back', raw_products_path