config/routes.rb
ProductCatalog::Application.routes.draw do
  resources :raw_products

  resources :units

  resources :products

  resources :items

  resources :categories

  authenticated :user do
    root :to => 'items#index'
  end

  root :to => "home#index"

  devise_for :users

  resources :users, :only => [:show, :index]
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :properties, :length, :memory_id, :pieces_per_package, :product_id, :vendor_sku, :comment, :vendor_name, :unit_ids

  validates :vendor_sku, :presence => true, :uniqueness => true

  has_and_belongs_to_many :units
  has_many :products, :through => :units
  belongs_to :product
  has_one :category, :through => :product

  default_scope :order => 'vendor_sku ASC'

  def name
    "#{(properties.blank? ? vendor_name : properties)} [#{vendor_sku}]"
  end

  def category_name
    unless product.blank?
      unless product.category.blank?
        category.name
      else
        'add category'
      end
    else
      'add product'
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :category_id, :comment, :minimum_order, :name, :per_unit, :store_sku, :unit_price

  validates :name, :store_sku, :presence => true

  belongs_to :category
  has_many :items
  has_many :units

  default_scope :order => 'name ASC'
  scope :uncategorized, where("category_id IS NULL")

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  load_and_authorize_resource

  # GET /items
  # GET /items.json
  def index
    @items = Item.paginate(:page => params[:page], :per_page => 100)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to edit_item_path(@item), notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to (@item.units.any? ? items_path : edit_item_path(@item)), notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= bootstrap_form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg

  = f.text_field :vendor_sku
  = f.text_field :vendor_name
  = f.collection_select :product_id, Product.all, :id, :name
  = f.text_field :length
  - if f.object.product
    = f.collection_check_boxes :unit_ids, f.object.product.units.all, :id, :name
    - unless f.object.product.units.any?
      %p
        You need to
        = link_to 'create units', new_unit_path
        for the product.
  - else
    %p You need to save this item with a product.
  = f.text_field :properties
  = f.number_field :pieces_per_package
  = f.number_field :memory_id
  = f.text_area :comment, :rows => 3
  = f.submit 'Save'

app/views/items/_item.html.haml
%li
  = link_to item.properties, item
  = item.vendor_sku
  = link_to 'edit', edit_item_path(item)
  = item.comment

app/views/items/edit.html.haml
%h1 Editing item

= render 'form'

= link_to 'Show', @item
\|
= link_to 'Back', items_path

app/views/items/index.html.haml
= link_to 'New Item', new_item_path
= will_paginate :class => 'pagination pagination-centered'
%table.table.table-striped.table-condensed.table-bordered
  %tr
    %th Category
    %th Product
    %th Units
    %th pcs/pkg
    %th Length
    %th Memory
    %th Properties
    %th Vendor SKU
    %th Vendor Name
    %th Comment
    %th

  - @items.each do |item|
    %tr{:class => (item.units.any? ? (item.products.count > 1 ? 'info' : 'success') : 'error')}
      %td
        - if item.category
          = link_to item.category.name, item.category
        - elsif item.product
          = link_to 'add category', edit_product_path(item.product)
        - else
          = link_to 'add to product', edit_item_path(item)
      %td
        -if item.product
          = link_to item.product.name, item.product
        - else
          = link_to 'add to product', edit_item_path(item)
      %td
        %ul
          - for unit in item.units do
            %li= link_to unit.pricing, edit_unit_path(unit)
      %td= item.pieces_per_package
      %td= item.length
      %td= item.memory_id
      %td= item.properties
      %td
        =link_to item.vendor_sku, edit_item_path(item)
      %td= item.vendor_name
      %td= item.comment
      %td= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }
= will_paginate :class => 'pagination pagination-centered'

app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

app/views/items/show.html.haml
%p#notice= notice

.page-header
  %h1
    = @item.properties
    %small
      = @item.product.name if @item.product
%dl.dl-horizontal
  %dt pcs/pkg:
  %dd= @item.pieces_per_package
  %dt Properties:
  %dd= @item.properties
  %dt Vendor SKU:
  %dd= @item.vendor_sku
  %dt Vendor Name:
  %dd= @item.vendor_name
  %dt Comment:
  %dd= @item.comment
%ul
  = render @item.products

= link_to 'Edit', edit_item_path(@item)
\|
= link_to 'Back', items_path