config/routes.rb
ProductCatalog::Application.routes.draw do
  resources :raw_products

  resources :units

  resources :products

  resources :items

  resources :categories

  authenticated :user do
    root :to => 'items#index'
  end

  root :to => "home#index"

  devise_for :users

  resources :users, :only => [:show, :index]
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :comment, :name

  validates :name, :presence => true
  
  has_many :products
  has_many :units, :through => :products
  has_many :items, :through => :products

  default_scope :order => 'name ASC'

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :comment
    = f.text_area :comment, :rows => 3
  .actions
    = f.submit 'Save'

app/views/categories/_menu.html.haml
= link_to 'new category', new_category_path if can? :create, Category

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%ul
  - for category in @categories do
    %li
      %h1
        = category.name
        %small
          = category.comment
          = link_to 'view', category
          = link_to 'edit', edit_category_path(category)
      %ul
        = render category.products
%hr
%h1 Uncategorized Products
%ul
  - for product in Product.uncategorized.all do
    = render product

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

.page-header
  %h1
    = @category.name
    %small #{pluralize(@category.products.count, 'product')}, #{pluralize(@category.units.count, 'unit')}, #{pluralize(@category.items.count, 'item')}
%p
  = @category.comment

%ul= render @category.products

= link_to 'Edit', edit_category_path(@category)