config/routes.rb
ProductCatalog::Application.routes.draw do
  resources :raw_products

  resources :units

  resources :products

  resources :items

  resources :categories

  authenticated :user do
    root :to => 'items#index'
  end

  root :to => "home#index"

  devise_for :users

  resources :users, :only => [:show, :index]
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to "MounceEndo Product Catalog", root_path, :class => 'brand'
%ul.nav
  %li= link_to 'Categories', categories_path if can? :read, Category
  %li= link_to 'Products', products_path if can? :read, Product
  %li= link_to 'Units', units_path if can? :read, Unit
  %li= link_to 'Items', items_path if can? :read, Item
%ul.nav.pull-right
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', users_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
<!doctype html>
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "MounceEndo Product Catalog"
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container-fluid
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container-fluid
        .row-fluid
          .span12
            = render 'menu' rescue nil
        .row-fluid
          .span12
            = render 'layouts/messages'
            = yield
          %footer
      / ! end of .container
    / ! end of #main